contact_links:
    - name: ❓ Questions and Help 🤔
      url: https://discord.gg/cyware (/add your discord channel if applicable)
      about: This issue tracker is not for support questions. Please refer to the community for more help. 
